version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: online_market_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      - online_market_network
    ports:
      - "5433:5432"

  web:
    build:
      context: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: online_market_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 54321
    depends_on:
      - db
    networks:
      - online_market_network
    ports:
      - "8000:8000"

networks:
  online_market_network:
    driver: bridge
